### ISSUE TITLE
Why `eps_sigma[t]*sigma_phi` on line 281 of `twostate.stan`?

### ISSUE THREAD

**Issue by mqwilber** [SNARL1/mrmr#21]
I am extracting survival probabilities from model fits of the `mrmr` package and couldn't figure out why line 281 in `twostate.stan` has `eps_sigma[t]*sigma_phi` rather than just `eps_sigma[t]` as on line 42?

**Comment by mbjoseph** [comment]
Good catch! I suspect I introduced this bug when updating the program to use the new offset/multiplier syntax. Looks like I updated it in the likelihood but not the generated quantities. The term we want on 281 should just be `eps_sigma[t]`.

Fixed in #22
