### ISSUE TITLE
clean_data() needs 'people' in surveys table

### ISSUE THREAD

**Issue by TomCSmith** [SNARL1/mrmr#8]
According to https://snarl1.github.io/mrmr/reference/clean_data.html, in the `surveys` table, only columns `survey_date`, `primary_period`, and `secondary_period` are necessary.

When using a `survey` table that includes only these columns, I get the error "Error: Column `people` not found in `.data`"

**Comment by mbjoseph** [comment]
Thanks @TomCSmith! This is fixed with https://github.com/SNARL1/mrmr/commit/085ca0ca1551e7c9cdd77a1c7bd96d0567ba241a
